<?php
session_start();
require_once __DIR__ . DIRECTORY_SEPARATOR . 'db.php';
if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'client') {
    header('Location: index.php');
    exit;
}

$user = $_SESSION['user'];
$database = db();
$content = ['announcements' => $database->query("SELECT title, details AS body, image_path, video_path FROM content WHERE type = 'announcement' ORDER BY id DESC")->fetchAll(), 'courses' => $database->query("SELECT title, details, image_path, video_path FROM content WHERE type = 'course' ORDER BY id DESC")->fetchAll(), 'consultancy' => $database->query("SELECT title, details, image_path, video_path FROM content WHERE type = 'consultancy' ORDER BY id DESC")->fetchAll()];
$requestMessage = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $requestType = $_POST['request_type'] ?? '';
  $allowedTypes = ['admission', 'training', 'consultancy', 'feedback'];
  if (in_array($requestType, $allowedTypes, true)) {
    $statement = $database->prepare('INSERT INTO requests (id, name, username, type, subject, message, status, payment_status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)');
    $statement->execute([uniqid('brd_', true), $user['name'], $user['username'], $requestType, trim((string) ($_POST['subject'] ?? $_POST['course'] ?? '')), trim((string) ($_POST['message'] ?? '')), 'Submitted', $requestType === 'admission' ? 'Pending' : 'Not applicable', date('Y-m-d H:i:s')]);
    $requestMessage = 'Your request was submitted successfully. BRD will update its status here.';
  }
}

$statement = $database->prepare('SELECT * FROM requests WHERE username = ? ORDER BY created_at DESC');
$statement->execute([$user['username']]);
$myRequests = $statement->fetchAll();
$esc = static fn ($value) => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$name = htmlspecialchars($user['name'], ENT_QUOTES, 'UTF-8');
$username = htmlspecialchars($user['username'], ENT_QUOTES, 'UTF-8');
$initial = htmlspecialchars(strtoupper(substr($user['name'], 0, 1)), ENT_QUOTES, 'UTF-8');
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Client workspace | BRD Research Consulting Centre</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="styles.css">
  <style>
    .course-media{display:block;width:100%;max-height:190px;object-fit:cover;margin:-20px -20px 16px;width:calc(100% + 40px)}.course-apply{display:inline-block;margin-top:14px;color:var(--navy);font-size:12px;font-weight:700;text-decoration:none}.course-apply span{padding-left:5px}
    .client-notice{margin:0 0 24px;padding:16px 20px;background:#e6f0e8;border-left:4px solid var(--green);color:var(--green);font-size:13px}.client-notice:empty{display:none}.client-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:30px 0}.client-card{padding:22px;background:#fff;border-top:4px solid var(--red)}.client-card:nth-child(2){border-color:var(--green)}.client-card:nth-child(3){border-color:var(--navy)}.client-card:nth-child(4){border-color:#d09a20}.client-card strong{display:block;color:var(--navy);font:600 38px/1 "Barlow Condensed",sans-serif}.client-card span{display:block;margin-top:8px;color:var(--muted);font-size:12px}.client-section{margin-top:26px;padding:30px;background:#fff}.client-section h2{margin:0 0 20px;color:var(--navy);font:600 36px/1 "Barlow Condensed",sans-serif;text-transform:uppercase}.announcement-list,.course-list{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.announcement,.course{padding:20px;background:var(--cream);border-left:3px solid var(--red)}.announcement h3,.course h3{margin:0 0 8px;font-size:15px}.announcement p,.course p{margin:0;color:var(--muted);font-size:12px;line-height:1.6}.portal-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:22px}.portal-form{padding:30px;background:var(--navy);color:#fff}.portal-form.green-form{background:var(--green)}.portal-form h2{margin:0 0 8px;color:#fff}.portal-form p{margin:0 0 18px;color:#d5d9e8;font-size:12px;line-height:1.6}.portal-form label{display:block;margin:12px 0;font-size:12px;font-weight:700}.portal-form input,.portal-form select,.portal-form textarea{display:block;width:100%;margin-top:6px;padding:11px;border:0;background:#fff;color:var(--ink);font:13px "DM Sans",sans-serif}.portal-form textarea{min-height:82px;resize:vertical}.portal-form button{margin-top:10px;border:0;cursor:pointer}.portal-form button span{float:right}.request-list{margin-top:22px;border-top:1px solid #d9dcd7}.request-row{display:grid;grid-template-columns:1.3fr .7fr .7fr .8fr;gap:12px;padding:14px 0;border-bottom:1px solid #d9dcd7;font-size:12px;align-items:center}.request-row strong{color:var(--navy)}.request-status{color:var(--green);font-weight:700}.process{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;counter-reset:step}.process-step{padding:22px 16px 16px;background:var(--cream);font-size:12px;color:var(--muted);line-height:1.5}.process-step:before{counter-increment:step;content:"0" counter(step);display:block;margin-bottom:18px;color:var(--red);font:600 28px/1 "Barlow Condensed",sans-serif}.process-step strong{display:block;margin-bottom:6px;color:var(--navy);font-size:14px}
    .client-shell{min-height:100vh;background:var(--cream)}
    .client-header{max-width:1240px;margin:auto;padding:26px 32px;border-bottom:1px solid #d9dcd7;display:flex;justify-content:space-between;align-items:center}.client-header .brand-mark{transform:scale(.84);transform-origin:left top;margin-bottom:-5px}.client-header .brand-subtitle{font-size:8px}.client-user{display:flex;align-items:center;gap:14px;color:var(--muted);font-size:13px}.client-initial{display:grid;place-items:center;width:40px;height:40px;background:var(--green);border-radius:50%;color:#fff;font-weight:700}.client-main{max-width:1240px;margin:auto;padding:56px 32px 84px}.client-hero{display:flex;justify-content:space-between;gap:30px;align-items:end;margin-bottom:38px}.client-hero h1{max-width:700px;margin:12px 0;color:var(--navy);font:600 clamp(52px,7vw,84px)/.88 "Barlow Condensed",sans-serif;text-transform:uppercase}.client-hero p:not(.eyebrow){max-width:570px;color:var(--muted);line-height:1.7}.client-date{color:var(--red);font-size:12px;font-weight:700;letter-spacing:1px;text-transform:uppercase;white-space:nowrap}.client-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:22px}.client-panel{padding:30px;background:#fff;border-top:4px solid var(--navy)}.client-panel h2{margin:0 0 20px;color:var(--navy);font:600 34px/1 "Barlow Condensed",sans-serif;text-transform:uppercase}.project{padding:18px 0;border-top:1px solid #d9dcd7;display:flex;justify-content:space-between;gap:20px}.project h3{margin:0 0 6px;font-size:15px}.project p{margin:0;color:var(--muted);font-size:12px}.tag{align-self:start;padding:7px 9px;background:#e9e4d5;color:var(--green);font-size:10px;font-weight:700;text-transform:uppercase;white-space:nowrap}.account-panel{border-color:var(--green)}.account-row{display:flex;justify-content:space-between;gap:18px;padding:13px 0;border-top:1px solid #d9dcd7;font-size:13px}.account-row span:first-child{color:var(--muted)}.account-row span:last-child{font-weight:700;text-align:right}.masked{letter-spacing:2px}.admissions{margin-top:22px;padding:30px;background:var(--navy);color:#fff}.admissions h2{margin:0 0 8px;font:600 36px/1 "Barlow Condensed",sans-serif;text-transform:uppercase}.admissions-intro{margin:0 0 22px;color:#d5d9e8;font-size:13px;line-height:1.6}.admission-list{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.admission-link{display:flex;min-height:120px;padding:16px;background:#ffffff12;border:1px solid #ffffff33;color:#fff;text-decoration:none;flex-direction:column;justify-content:space-between}.admission-link strong{font-size:14px}.admission-link span{color:#e7bc42;font-size:12px}.client-footer{max-width:1240px;margin:auto;padding:0 32px 28px;color:var(--muted);font-size:12px;display:flex;justify-content:space-between}.client-footer a{color:var(--navy);font-weight:700;text-decoration:none}
    @media(max-width:760px){.client-header{padding:22px 20px}.client-user{gap:8px}.client-user>span:first-child{display:none}.client-main{padding:42px 20px 60px}.client-hero{display:block}.client-date{display:block;margin-top:22px}.client-grid{display:block}.account-panel{margin-top:22px}.admission-list{grid-template-columns:1fr}.client-footer{padding:0 20px 22px;display:block}.client-footer p{margin-bottom:10px}}
  </style>
</head>
<body>
  <div class="topline"></div>
  <div class="client-shell">
    <header class="client-header">
      <a class="brand" href="index.php" aria-label="BRD home"><span class="brand-mark"><b>B</b><b class="torch">R<span>●</span></b><b>D<i>••</i></b></span><span class="brand-subtitle">Building Resilience to Disasters</span></a>
      <div class="client-user"><span><?= $name ?></span><span class="client-initial"><?= $initial ?></span><a class="text-link" href="profile.php">Profile <span>→</span></a><a class="text-link" href="logout.php">Sign out <span>↗</span></a></div>
    </header>
    <main class="client-main">
      <section class="client-hero"><div><p class="eyebrow">Client workspace</p><h1>Your research, clearly in view.</h1><p>Track your projects, keep your documents close, and find trusted admissions resources from one place.</p></div><span class="client-date"><?= date('F j, Y') ?></span></section>
      <p class="client-notice"><?= $esc($requestMessage) ?></p>
      <section class="client-cards" aria-label="Client overview"><div class="client-card"><strong><?= count($myRequests) ?></strong><span>Requests submitted</span></div><div class="client-card"><strong><?= count(array_filter($myRequests, static fn ($item) => ($item['status'] ?? '') === 'Approved')) ?></strong><span>Approved requests</span></div><div class="client-card"><strong><?= count(array_filter($myRequests, static fn ($item) => ($item['payment_status'] ?? '') === 'Paid')) ?></strong><span>Payments completed</span></div><div class="client-card"><strong><?= count($content['announcements']) ?></strong><span>New BRD updates</span></div></section>
      <div class="client-grid">
        <section class="client-panel" aria-labelledby="projects-title"><h2 id="projects-title">Your projects</h2><article class="project"><div><h3>Community resilience baseline</h3><p>Data collection · 68% complete · Updated today</p></div><span class="tag">Active</span></article><article class="project"><div><h3>Market access study</h3><p>Research design · BRD review in progress</p></div><span class="tag">Review</span></article><article class="project"><div><h3>Training evaluation</h3><p>Results shared · 14 August</p></div><span class="tag">Complete</span></article></section>
        <aside class="client-panel account-panel" aria-labelledby="account-title"><h2 id="account-title">Account details</h2><div class="account-row"><span>Full name</span><span><?= $name ?></span></div><div class="account-row"><span>Username</span><span><?= $username ?></span></div><div class="account-row"><span>Role</span><span>Client</span></div><div class="account-row"><span>Password</span><span class="masked">••••••••</span></div></aside>
      </div>
      <section class="admissions" aria-labelledby="admissions-title"><h2 id="admissions-title">Admissions sites</h2><p class="admissions-intro">Use these official portals to explore programmes, applications, technical education, and student funding. BRD does not collect or store your admissions passwords.</p><div class="admission-list"><a class="admission-link" href="https://www.tcu.go.tz/" target="_blank" rel="noopener"><strong>Tanzania Commission for Universities</strong><span>Open official site ↗</span></a><a class="admission-link" href="https://www.nactvet.go.tz/" target="_blank" rel="noopener"><strong>NACTVET</strong><span>Open official site ↗</span></a><a class="admission-link" href="https://www.heslb.go.tz/" target="_blank" rel="noopener"><strong>HESLB student loans</strong><span>Open official site ↗</span></a></div></section>
      <section class="client-section" aria-labelledby="updates-title"><h2 id="updates-title">What BRD has posted</h2><div class="announcement-list"><?php foreach ($content['announcements'] as $announcement): ?><article class="announcement"><h3><?= $esc($announcement['title'] ?? '') ?></h3><p><?= $esc($announcement['body'] ?? '') ?></p></article><?php endforeach; ?><?php if (!$content['announcements']): ?><p>No announcements have been posted yet.</p><?php endif; ?></div></section>
      <section class="client-section" aria-labelledby="training-title"><h2 id="training-title">Research training &amp; courses</h2><div class="course-list"><?php foreach ($content['courses'] as $course): ?><article class="course"><?php if (!empty($course['image_path'])): ?><img class="course-media" src="<?= $esc($course['image_path']) ?>" alt="<?= $esc($course['title'] ?? '') ?> course image"><?php endif; ?><?php if (!empty($course['video_path'])): ?><video class="course-media" controls preload="metadata"><source src="<?= $esc($course['video_path']) ?>"></video><?php endif; ?><h3><?= $esc($course['title'] ?? '') ?></h3><p><?= $esc($course['details'] ?? '') ?></p><a class="course-apply" href="#admission-form">Apply for this course <span>→</span></a></article><?php endforeach; ?><?php if (!$content['courses']): ?><p>Training announcements will appear here when published.</p><?php endif; ?></div></section>
      <section class="client-section" aria-labelledby="consultancy-title"><h2 id="consultancy-title">Consultancy services</h2><div class="course-list"><?php foreach ($content['consultancy'] as $service): ?><article class="course"><h3><?= $esc($service['title'] ?? '') ?></h3><p><?= $esc($service['details'] ?? '') ?></p><a class="course-apply" href="#consultancy-form">Request this service <span>→</span></a></article><?php endforeach; ?><?php if (!$content['consultancy']): ?><p>Consultancy services will appear here when published.</p><?php endif; ?></div></section>
      <section class="client-section" aria-labelledby="process-title"><h2 id="process-title">How admission works</h2><div class="process"><div class="process-step"><strong>Apply</strong>Choose a course, consultancy service, or admission programme and submit your request.</div><div class="process-step"><strong>Review</strong>BRD reviews your requirements and may request additional information.</div><div class="process-step"><strong>Payment</strong>When approved, payment instructions and confirmation are shared securely.</div><div class="process-step"><strong>Attend</strong>Receive your admission confirmation, schedule, and training or consultancy access.</div></div></section>
      <div class="portal-grid"><form class="portal-form" id="admission-form" method="post"><input type="hidden" name="request_type" value="admission"><h2>Apply for admission</h2><p>Apply for an announced training course or research programme. Your request will appear in your status list below.</p><label>Course or programme<select name="course" required><option value="">Select an option</option><?php foreach ($content['courses'] as $course): ?><option><?= $esc($course['title'] ?? '') ?></option><?php endforeach; ?><option>Research methodology training</option><option>Research consultancy orientation</option></select></label><label>Message<textarea name="message" placeholder="Tell BRD about your goals and background" required></textarea></label><button class="button button-light" type="submit">Submit application <span>→</span></button></form><form class="portal-form green-form" id="consultancy-form" method="post"><input type="hidden" name="request_type" value="consultancy"><h2>Request consultancy</h2><p>Ask for support with research design, data analysis, training, GIS, or another BRD service.</p><label>Service needed<input name="subject" placeholder="Example: SPSS data analysis" required></label><label>Message<textarea name="message" placeholder="Describe your requirements" required></textarea></label><button class="button button-light" type="submit">Send request <span>→</span></button></form></div>
      <form class="client-section" method="post"><input type="hidden" name="request_type" value="feedback"><h2>Send feedback</h2><label>Subject<input name="subject" placeholder="What would you like to tell BRD?" required></label><label>Message<textarea name="message" placeholder="Share feedback or ask a question" required></textarea></label><button class="button button-red" type="submit">Send feedback <span>→</span></button></form>
      <section class="client-section" aria-labelledby="requests-title"><h2 id="requests-title">Your request status</h2><div class="request-list"><?php foreach ($myRequests as $request): ?><div class="request-row"><strong><?= $esc(ucfirst($request['type'])) ?></strong><span><?= $esc($request['subject'] ?: 'General request') ?></span><span class="request-status"><?= $esc($request['status']) ?></span><span><?= $esc($request['payment_status']) ?></span></div><?php endforeach; ?><?php if (!$myRequests): ?><p>No requests yet. Use the application or consultancy forms above.</p><?php endif; ?></div></section>
    </main>
    <footer class="client-footer"><p>BRD Research Consulting Centre · Client workspace</p><a href="index.php#contact">Need support? Contact BRD ↗</a></footer>
  </div>
</body>
</html>
