<?php
session_start();
require_once __DIR__ . DIRECTORY_SEPARATOR . 'db.php';
if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'admin') { header('Location: index.php'); exit; }
$id = trim((string) ($_GET['id'] ?? ''));
$statement = db()->prepare('SELECT * FROM requests WHERE id = ? LIMIT 1');
$statement->execute([$id]);
$request = $statement->fetch();
if (!$request) { http_response_code(404); exit('Request not found.'); }
$esc = static fn ($value) => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Request record | BRD</title><link rel="stylesheet" href="styles.css"><style>.record-shell{min-height:100vh;background:var(--cream)}.record-header,.record-main,.record-footer{max-width:900px;margin:auto}.record-header{padding:26px 32px;border-bottom:1px solid #d9dcd7;display:flex;justify-content:space-between}.record-main{padding:56px 32px}.record-card{background:#fff;padding:30px;border-top:4px solid var(--red)}.record-card h1{margin:10px 0 25px;color:var(--navy);font:600 60px/.9 'Barlow Condensed',sans-serif;text-transform:uppercase}.record-row{display:flex;justify-content:space-between;gap:20px;padding:14px 0;border-top:1px solid #d9dcd7;font-size:13px}.record-row span:first-child{color:var(--muted)}.record-message{margin-top:20px;padding:20px;background:var(--cream);white-space:pre-wrap;line-height:1.7}.record-footer{padding:0 32px 28px;color:var(--muted);font-size:12px}@media(max-width:700px){.record-header,.record-main,.record-footer{padding-left:20px;padding-right:20px}.record-row{display:block}.record-row span{display:block;margin:4px 0}}
</style></head><body><div class="topline"></div><div class="record-shell"><header class="record-header"><a class="brand" href="manage.php"><span class="brand-mark"><b>B</b><b class="torch">R<span>●</span></b><b>D<i>••</i></b></span><span class="brand-subtitle">Building Resilience to Disasters</span></a><a class="text-link" href="manage.php">Back to operations <span>↗</span></a></header><main class="record-main"><p class="eyebrow">Full request record</p><section class="record-card"><h1><?= $esc($request['subject'] ?: ucfirst($request['type'])) ?></h1><div class="record-row"><span>Applicant</span><strong><?= $esc($request['name']) ?></strong></div><div class="record-row"><span>Email</span><strong><?= $esc($request['email'] ?? '') ?></strong></div><div class="record-row"><span>Phone</span><strong><?= $esc($request['phone'] ?? '') ?></strong></div><div class="record-row"><span>Request type</span><strong><?= $esc(ucfirst($request['type'])) ?></strong></div><div class="record-row"><span>Course / programme</span><strong><?= $esc($request['course_name'] ?? '') ?></strong></div><div class="record-row"><span>Duration</span><strong><?= $esc($request['duration'] ?? '') ?></strong></div><div class="record-row"><span>Status</span><strong><?= $esc($request['status']) ?> · <?= $esc($request['payment_status']) ?></strong></div><div class="record-row"><span>Submitted</span><strong><?= $esc($request['created_at']) ?></strong></div><div class="record-message"><?= $esc($request['message']) ?></div></section></main><footer class="record-footer">BRD Research Consulting Centre · confidential request record</footer></div></body></html>
